name: Trade Signal Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # každých 5 minút
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests
      - name: Run trade signal script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          START_CAPITAL: 100
          MIN_PROFIT_EUR: 1
          TRAIL_DROP: 0.01
        run: python trade_signal.py
      - name: Commit updated state.json
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state.json
            git commit -m "Update state.json (trade signal bot)"
            git push
          else
            echo "No changes to commit."
          fi

